
import { CarRental } from './types';

export const MOCK_CARS: CarRental[] = [
  {
    id: 'store-1',
    district: '元朗區',
    model: '豐田 Comfort Hybrid',
    brand: 'Toyota',
    year: 2024,
    seats: 4,
    condition: '全新車隊',
    morningPrice: 520,
    eveningPrice: 500,
    deposit: 8000,
    companyName: '誠信車行 (元朗店)',
    companyColor: 'green',
    tagline: "Hong Kong's Top Rated 2025. Super Clean Fleet.",
    isVerifiedStore: true,
    websiteUrl: '/store/integrity-taxi-yuen-long',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'HYBRID',
    rating: 4.9,
    reviewCount: 2450,
    topReview: {
      id: 'r1',
      userName: '阿輝',
      userImage: 'https://i.pravatar.cc/150?u=ahfai',
      rating: 5,
      comment: "架車真係好乾淨，混能車慳油好力，元朗取車好方便。",
      date: 'Jan 2026',
      isVerified: true,
    },
    taxiType: '綠的',
    ageRange: '1-2年',
    distanceKm: 2.4
  },
  {
    id: 'store-2',
    district: '黃大仙區',
    model: '豐田 Comfort Hybrid',
    brand: 'Toyota',
    year: 2023,
    seats: 5,
    condition: '良好保養',
    morningPrice: 480,
    eveningPrice: 480,
    deposit: 0,
    companyName: '聯樂的士管理 (黃大仙)',
    companyColor: 'red',
    tagline: "Flexible Rental. No Deposit for Verified Members.",
    isVerifiedStore: true,
    websiteUrl: '/store/luen-lok-wong-tai-sin',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'HYBRID',
    rating: 4.7,
    reviewCount: 1820,
    topReview: {
      id: 'r2',
      userName: 'Sarah Wong',
      userImage: 'https://i.pravatar.cc/150?u=sarahw',
      rating: 5,
      comment: "免按金真係減輕左好多負擔，黃大仙地鐵站行過去幾分鐘就到。",
      date: 'Feb 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '1-2年',
    distanceKm: 5.8
  },
  {
    id: 'store-3',
    district: '荃灣區',
    model: '福特 Transit Connect',
    brand: 'Ford',
    year: 2024,
    seats: 5,
    condition: '頂級配置',
    morningPrice: 550,
    eveningPrice: 550,
    deposit: 12000,
    companyName: '桑富貿易 (荃灣)',
    companyColor: 'red', // Updated from blue to red
    tagline: "New 2024 Models Available. 24/7 Roadside Support.",
    isVerifiedStore: true,
    websiteUrl: '/store/sang-foo-tsuen-wan',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=400',
    category: 'LTO',
    rating: 4.8,
    reviewCount: 960,
    topReview: {
      id: 'r3',
      userName: 'Michael Chan',
      userImage: 'https://i.pravatar.cc/150?u=mchan',
      rating: 5,
      comment: "架Ford車廂好闊落，桑富服務一向有保證，有事打去24小時熱線即刻有人聽。",
      date: 'Jan 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '1-2年',
    distanceKm: 1.2
  },
  {
    id: 'store-4',
    district: '深水埗區',
    model: '豐田 Crown Comfort',
    brand: 'Toyota',
    year: 2021,
    seats: 5,
    condition: '經典耐操',
    morningPrice: 420,
    eveningPrice: 400,
    deposit: 5000,
    companyName: '嘉訊租車',
    companyColor: 'red',
    tagline: "Classic Reliability. Best Value in Kowloon.",
    isVerifiedStore: true,
    websiteUrl: '/store/ka-shun-ssp',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'CLASSIC',
    rating: 4.5,
    reviewCount: 3200,
    topReview: {
      id: 'r4',
      userName: 'James Li',
      userImage: 'https://i.pravatar.cc/150?u=jamesli',
      rating: 4,
      comment: "雖然係舊款車，但保養得唔錯，價錢最平。",
      date: 'Mar 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '3-5年',
    distanceKm: 8.9
  },
  {
    id: 'store-5',
    district: '大埔區',
    model: '日產 NOTE e-POWER',
    brand: 'Nissan',
    year: 2024,
    seats: 5,
    condition: '節能之選',
    morningPrice: 490,
    eveningPrice: 490,
    deposit: 6000,
    companyName: '新界動力',
    companyColor: 'green',
    tagline: "Eco-friendly driving. Instant confirmation.",
    isVerifiedStore: true,
    websiteUrl: '/store/nt-power-tp',
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&q=80&w=400',
    category: 'ELECTRIC',
    rating: 4.8,
    reviewCount: 450,
    topReview: {
      id: 'r5',
      userName: '大埔豪哥',
      userImage: 'https://i.pravatar.cc/150?u=hao',
      rating: 5,
      comment: "e-POWER 好好力，而且慳油錢。新界區首選。",
      date: 'Apr 2026',
      isVerified: true,
    },
    taxiType: '綠的',
    ageRange: '1-2年',
    distanceKm: 0.8
  },
  {
    id: 'store-6',
    district: '油尖旺區',
    model: '日產 NV200',
    brand: 'Nissan',
    year: 2022,
    seats: 5,
    condition: '特大空間',
    morningPrice: 460,
    eveningPrice: 460,
    deposit: 3000,
    companyName: '旺角聯合',
    companyColor: 'red',
    tagline: "Massive storage. Perfect for airport runs.",
    isVerifiedStore: true,
    websiteUrl: '/store/mk-united',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=400',
    category: 'VAN',
    rating: 4.6,
    reviewCount: 1100,
    topReview: {
      id: 'r6',
      userName: 'Kowloon Driver',
      userImage: 'https://i.pravatar.cc/150?u=kd',
      rating: 5,
      comment: "NV200 空間真係無敵，放幾件大行李都無問題。",
      date: 'Feb 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '3-5年',
    distanceKm: 4.5
  },
  {
    id: 'store-7',
    district: '東涌/離島',
    model: '豐田 Comfort Hybrid',
    brand: 'Toyota',
    year: 2024,
    seats: 4,
    condition: '藍的旗艦',
    morningPrice: 580,
    eveningPrice: 580,
    deposit: 15000,
    companyName: '大嶼山車隊',
    companyColor: 'blue',
    tagline: "Island specialized. Premium blue taxi service.",
    isVerifiedStore: true,
    websiteUrl: '/store/lantau-fleet',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'HYBRID',
    rating: 4.9,
    reviewCount: 880,
    topReview: {
      id: 'r7',
      userName: 'Blue Sky',
      userImage: 'https://i.pravatar.cc/150?u=sky',
      rating: 5,
      comment: "架車好靜，去機場或者東涌周圍走好舒服。",
      date: 'May 2026',
      isVerified: true,
    },
    taxiType: '藍的',
    ageRange: '1-2年',
    distanceKm: 12.0
  },
  {
    id: 'store-8',
    district: '九龍城區',
    model: '豐田 Comfort Hybrid',
    brand: 'Toyota',
    year: 2023,
    seats: 4,
    condition: '頂級隔音',
    morningPrice: 500,
    eveningPrice: 490,
    deposit: 5000,
    companyName: '九龍城租車總匯',
    companyColor: 'red',
    tagline: "Center of Kowloon. Easy pick-up 24/7.",
    isVerifiedStore: true,
    websiteUrl: '/store/kc-rental',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'HYBRID',
    rating: 4.7,
    reviewCount: 2200,
    topReview: {
      id: 'r8',
      userName: 'Mike',
      userImage: 'https://i.pravatar.cc/150?u=mike',
      rating: 5,
      comment: "租左成年，車況一直好穩定，維修保養跟得足。",
      date: 'Mar 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '1-2年',
    distanceKm: 6.2
  },
  {
    id: 'store-9',
    district: '沙田區',
    model: '日產 NOTE e-POWER',
    brand: 'Nissan',
    year: 2023,
    seats: 5,
    condition: '極致省油',
    morningPrice: 470,
    eveningPrice: 450,
    deposit: 2000,
    companyName: '沙田龍頭',
    companyColor: 'green',
    tagline: "Budget-friendly, high tech driving experience.",
    isVerifiedStore: true,
    websiteUrl: '/store/st-dragon',
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&q=80&w=400',
    category: 'ELECTRIC',
    rating: 4.6,
    reviewCount: 340,
    topReview: {
      id: 'r9',
      userName: 'Sha Tin Fan',
      userImage: 'https://i.pravatar.cc/150?u=stf',
      rating: 4,
      comment: "平時跑沙田大埔非常適合，e-POWER慳翻好多氣錢。",
      date: 'Jan 2026',
      isVerified: true,
    },
    taxiType: '綠的',
    ageRange: '1-2年',
    distanceKm: 3.1
  },
  {
    id: 'store-10',
    district: '觀塘區',
    model: '豐田 Comfort Hybrid',
    brand: 'Toyota',
    year: 2024,
    seats: 4,
    condition: '全新上線',
    morningPrice: 530,
    eveningPrice: 530,
    deposit: 10000,
    companyName: '觀塘大業',
    companyColor: 'red',
    tagline: "Latest 2024 models. Professional dispatch.",
    isVerifiedStore: true,
    websiteUrl: '/store/kt-tai-yip',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'HYBRID',
    rating: 4.8,
    reviewCount: 150,
    topReview: {
      id: 'r10',
      userName: 'King of KT',
      userImage: 'https://i.pravatar.cc/150?u=king',
      rating: 5,
      comment: "呢間車行好公道，車又新，九龍東必選。",
      date: 'Apr 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '1-2年',
    distanceKm: 7.7
  },
  {
    id: 'store-11',
    district: '屯門區',
    model: '豐田 Comfort Hybrid',
    brand: 'Toyota',
    year: 2024,
    seats: 4,
    condition: '屯門首選',
    morningPrice: 510,
    eveningPrice: 490,
    deposit: 8000,
    companyName: '屯門興發',
    companyColor: 'green',
    tagline: "Tuen Mun district specialist. Fast check-out.",
    isVerifiedStore: true,
    websiteUrl: '/store/tm-hing-fat',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'HYBRID',
    rating: 4.7,
    reviewCount: 520,
    topReview: {
      id: 'r11',
      userName: 'TM Driver',
      userImage: 'https://i.pravatar.cc/150?u=tm',
      rating: 5,
      comment: "興發租車好多年喇，老牌子有信用。",
      date: 'Feb 2026',
      isVerified: true,
    },
    taxiType: '綠的',
    ageRange: '1-2年',
    distanceKm: 1.5
  },
  {
    id: 'store-12',
    district: '中西區',
    model: 'Tesla Model 3',
    brand: 'Tesla',
    year: 2024,
    seats: 5,
    condition: '純電極速',
    morningPrice: 650,
    eveningPrice: 650,
    deposit: 20000,
    companyName: '港島電力的',
    companyColor: 'red',
    tagline: "Pure Electric Luxury. Smart Dispatching.",
    isVerifiedStore: true,
    websiteUrl: '/store/island-electric',
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&q=80&w=400',
    category: 'ELECTRIC',
    rating: 4.9,
    reviewCount: 310,
    topReview: {
      id: 'r12',
      userName: 'EV King',
      userImage: 'https://i.pravatar.cc/150?u=ev',
      rating: 5,
      comment: "Tesla跑旗真係爽，慳翻油錢之餘乘客都坐得開心。",
      date: 'May 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '1-2年',
    distanceKm: 15.4
  },
  {
    id: 'store-13',
    district: '灣仔區',
    model: '豐田 Comfort Hybrid',
    brand: 'Toyota',
    year: 2023,
    seats: 4,
    condition: '繁華地段',
    morningPrice: 540,
    eveningPrice: 540,
    deposit: 5000,
    companyName: '灣仔信誠',
    companyColor: 'red',
    tagline: "Wan Chai central pick-up. No hassle.",
    isVerifiedStore: true,
    websiteUrl: '/store/wc-shun-shing',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'HYBRID',
    rating: 4.6,
    reviewCount: 1400,
    topReview: {
      id: 'r13',
      userName: 'Wanchai Guy',
      userImage: 'https://i.pravatar.cc/150?u=wc',
      rating: 4,
      comment: "位置好方便，收車之後直接搭地鐵返屋企都得。",
      date: 'Jan 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '1-2年',
    distanceKm: 13.8
  },
  {
    id: 'store-14',
    district: '西貢區',
    model: '日產 NOTE e-POWER',
    brand: 'Nissan',
    year: 2024,
    seats: 5,
    condition: '山區好力',
    morningPrice: 480,
    eveningPrice: 480,
    deposit: 3000,
    companyName: '西貢通達',
    companyColor: 'green',
    tagline: "Perfect for hilly NT roads. High torque.",
    isVerifiedStore: true,
    websiteUrl: '/store/sk-tung-tat',
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&q=80&w=400',
    category: 'ELECTRIC',
    rating: 4.8,
    reviewCount: 280,
    topReview: {
      id: 'r14',
      userName: 'SK Boy',
      userImage: 'https://i.pravatar.cc/150?u=skb',
      rating: 5,
      comment: "NOTE跑西貢斜路真係好爽，又靜又有力。",
      date: 'Mar 2026',
      isVerified: true,
    },
    taxiType: '綠的',
    ageRange: '1-2年',
    distanceKm: 2.1
  },
  {
    id: 'store-15',
    district: '離島區 (東涌)',
    model: '日產 NV200',
    brand: 'Nissan',
    year: 2023,
    seats: 5,
    condition: '機場專線',
    morningPrice: 560,
    eveningPrice: 560,
    deposit: 8000,
    companyName: '東涌捷通',
    companyColor: 'blue',
    tagline: "Cargo friendly. Specialized for Lantau/Airport.",
    isVerifiedStore: true,
    websiteUrl: '/store/tc-chit-tung',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=400',
    category: 'VAN',
    rating: 4.7,
    reviewCount: 410,
    topReview: {
      id: 'r15',
      userName: 'Airport Pro',
      userImage: 'https://i.pravatar.cc/150?u=ap',
      rating: 5,
      comment: "跑機場最緊要位大，NV200客人好滿意。",
      date: 'Apr 2026',
      isVerified: true,
    },
    taxiType: '藍的',
    ageRange: '1-2年',
    distanceKm: 11.5
  },
  {
    id: 'store-16',
    district: '北區',
    model: '豐田 Comfort Hybrid',
    brand: 'Toyota',
    year: 2023,
    seats: 4,
    condition: '邊境之選',
    morningPrice: 490,
    eveningPrice: 480,
    deposit: 5000,
    companyName: '上水聯邦',
    companyColor: 'green',
    tagline: "North district focal point. Professional management.",
    isVerifiedStore: true,
    websiteUrl: '/store/ss-union',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'HYBRID',
    rating: 4.6,
    reviewCount: 890,
    topReview: {
      id: 'r16',
      userName: 'North Side',
      userImage: 'https://i.pravatar.cc/150?u=ns',
      rating: 5,
      comment: "上水攞車好快，員工服務態度好好。",
      date: 'May 2026',
      isVerified: true,
    },
    taxiType: '綠的',
    ageRange: '1-2年',
    distanceKm: 3.8
  },
  {
    id: 'store-17',
    district: '南區',
    model: '日產 NOTE e-POWER',
    brand: 'Nissan',
    year: 2024,
    seats: 5,
    condition: '南區精品',
    morningPrice: 510,
    eveningPrice: 510,
    deposit: 4000,
    companyName: '香港仔管理',
    companyColor: 'red',
    tagline: "South Side specialists.",
    isVerifiedStore: true,
    websiteUrl: '/store/aberdeen-mgt',
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&q=80&w=400',
    category: 'ELECTRIC',
    rating: 4.8,
    reviewCount: 300,
    topReview: {
      id: 'r17',
      userName: 'S.Side Driver',
      userImage: 'https://i.pravatar.cc/150?u=ssd',
      rating: 5,
      comment: "香港仔攞車好方便，e-POWER慳好多。",
      date: 'Jun 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '1-2年',
    distanceKm: 16.5
  },
  {
    id: 'store-18',
    district: '東區',
    model: '豐田 Comfort Hybrid',
    brand: 'Toyota',
    year: 2023,
    seats: 4,
    condition: '柴灣基地',
    morningPrice: 495,
    eveningPrice: 495,
    deposit: 6000,
    companyName: '東區車會',
    companyColor: 'red',
    tagline: "Island East coverage.",
    isVerifiedStore: true,
    websiteUrl: '/store/island-east-taxi',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'HYBRID',
    rating: 4.7,
    reviewCount: 1250,
    topReview: {
      id: 'r18',
      userName: 'Chai Wan Joe',
      userImage: 'https://i.pravatar.cc/150?u=cwj',
      rating: 5,
      comment: "車行好專業，柴灣攞車唔使等。",
      date: 'July 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '1-2年',
    distanceKm: 14.2
  },
  {
    id: 'store-19',
    district: '西貢區',
    model: '日產 NV200',
    brand: 'Nissan',
    year: 2022,
    seats: 5,
    condition: '將軍澳支線',
    morningPrice: 470,
    eveningPrice: 470,
    deposit: 4000,
    companyName: 'TKO 聯合',
    companyColor: 'green',
    tagline: "TKO region focus.",
    isVerifiedStore: true,
    websiteUrl: '/store/tko-united',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=400',
    category: 'VAN',
    rating: 4.5,
    reviewCount: 600,
    topReview: {
      id: 'r19',
      userName: 'TKO Driver',
      userImage: 'https://i.pravatar.cc/150?u=tkod',
      rating: 4,
      comment: "將軍澳區少有嘅大車，保養得唔錯。",
      date: 'Aug 2026',
      isVerified: true,
    },
    taxiType: '綠的',
    ageRange: '3-5年',
    distanceKm: 3.5
  },
  {
    id: 'store-20',
    district: '大埔區',
    model: '豐田 Crown Comfort',
    brand: 'Toyota',
    year: 2019,
    seats: 5,
    condition: '經典實惠',
    morningPrice: 380,
    eveningPrice: 380,
    deposit: 2000,
    companyName: '大埔老牌車行',
    companyColor: 'green',
    tagline: "Affordable classic green taxi.",
    isVerifiedStore: false,
    websiteUrl: '/store/tp-classic',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'CLASSIC',
    rating: 4.3,
    reviewCount: 2000,
    topReview: {
      id: 'r20',
      userName: 'Uncle Seven',
      userImage: 'https://i.pravatar.cc/150?u=u7',
      rating: 4,
      comment: "價錢夠平，搵食首選。",
      date: 'Sept 2026',
      isVerified: true,
    },
    taxiType: '綠的',
    ageRange: '6-10年',
    distanceKm: 0.5
  },
  {
    id: 'store-21',
    district: '葵青區',
    model: '豐田 Comfort Hybrid',
    brand: 'Toyota',
    year: 2024,
    seats: 4,
    condition: '全新青衣車隊',
    morningPrice: 525,
    eveningPrice: 515,
    deposit: 7000,
    companyName: '青衣盈豐',
    companyColor: 'red',
    tagline: "Kwai Tsing specialists.",
    isVerifiedStore: true,
    websiteUrl: '/store/ty-ying-fung',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400',
    category: 'HYBRID',
    rating: 4.9,
    reviewCount: 180,
    topReview: {
      id: 'r21',
      userName: 'TY King',
      userImage: 'https://i.pravatar.cc/150?u=tyk',
      rating: 5,
      comment: "新車跑得好舒服，盈豐管理得好好。",
      date: 'Oct 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '1-2年',
    distanceKm: 2.7
  },
  {
    id: 'store-22',
    district: '觀塘區',
    model: '日產 NOTE e-POWER',
    brand: 'Nissan',
    year: 2023,
    seats: 5,
    condition: '觀塘環保先鋒',
    morningPrice: 485,
    eveningPrice: 485,
    deposit: 4500,
    companyName: '觀塘綠色出行',
    companyColor: 'red',
    tagline: "Eco-taxi in East Kowloon.",
    isVerifiedStore: true,
    websiteUrl: '/store/kt-green',
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&q=80&w=400',
    category: 'ELECTRIC',
    rating: 4.7,
    reviewCount: 290,
    topReview: {
      id: 'r22',
      userName: 'KT Guy',
      userImage: 'https://i.pravatar.cc/150?u=ktg',
      rating: 5,
      comment: "觀塘區少見e-POWER，非常好力。",
      date: 'Nov 2026',
      isVerified: true,
    },
    taxiType: '紅的',
    ageRange: '1-2年',
    distanceKm: 8.1
  },
  {
    id: 'store-23',
    district: '東涌/離島',
    model: '日產 NV200',
    brand: 'Nissan',
    year: 2024,
    seats: 5,
    condition: '大嶼山貨運皇',
    morningPrice: 590,
    eveningPrice: 590,
    deposit: 10000,
    companyName: '梅窩聯運',
    companyColor: 'blue',
    tagline: "Lantau's largest cargo taxi.",
    isVerifiedStore: true,
    websiteUrl: '/store/mw-united',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=400',
    category: 'VAN',
    rating: 4.8,
    reviewCount: 120,
    topReview: {
      id: 'r23',
      userName: 'Island Man',
      userImage: 'https://i.pravatar.cc/150?u=im',
      rating: 5,
      comment: "藍的NV200，去梅窩行山客最鍾意。",
      date: 'Dec 2026',
      isVerified: true,
    },
    taxiType: '藍的',
    ageRange: '1-2年',
    distanceKm: 14.8
  },
  {
    id: 'store-24',
    district: '元朗區',
    model: '福特 Transit Connect',
    brand: 'Ford',
    year: 2023,
    seats: 5,
    condition: '元朗歐美系',
    morningPrice: 540,
    eveningPrice: 540,
    deposit: 9000,
    companyName: '元朗歐美車行',
    companyColor: 'green',
    tagline: "Premium Ford fleet in YL.",
    isVerifiedStore: true,
    websiteUrl: '/store/yl-euro-taxi',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=400',
    category: 'LTO',
    rating: 4.7,
    reviewCount: 340,
    topReview: {
      id: 'r24',
      userName: 'Ford Fan',
      userImage: 'https://i.pravatar.cc/150?u=ff',
      rating: 5,
      comment: "Ford車真係好坐過豐田好多，歐美系首選。",
      date: 'Jan 2027',
      isVerified: true,
    },
    taxiType: '綠的',
    ageRange: '1-2年',
    distanceKm: 1.9
  }
];
